Repository galacticcouncil/HydraDX-math, pull requests merged in 2021-06, with the labels that each got.

#21 refactor: lbp without sp-arithmetic crate
  Cargo.lock
  Cargo.toml
  src/lbp/lbp.rs
Labels: refactor

#17 feat: lbp math
  .github/workflows/tests.yml
  Cargo.lock
  Cargo.toml
  src/amm.rs
  src/lbp/lbp.rs
  src/lbp/mod.rs
  src/lbp/tests.rs
  src/lbp/traits.rs
  src/lbp/types.rs
  src/lib.rs
  src/tests.rs
Labels: enhancement

#22 fix: rounding up
  Cargo.toml
  src/lib.rs
  src/tests.rs
  src/xyk.rs
Labels: bug

#23 ci: add code coverage
  .github/workflows/tests.yml
  Cargo.lock
Labels: ci
