Repository galacticcouncil/HydraDX-math, pull requests merged in 2022-09, with the labels that each got.

#48 feat: adjusted shares calculation
  .gitignore
  Cargo.lock
  Cargo.toml
  src/liquidity_mining/invariants.rs
  src/liquidity_mining/liquidity_mining.rs
  src/liquidity_mining/mod.rs
  src/liquidity_mining/tests.rs
  src/types.rs
Labels: enhancement

#57 ci: run clippy as make cmd
  .github/workflows/tests.yml
Labels: ci

#54 refactor: omnopool - use already calculated value
  src/omnipool/math.rs
Labels: refactor

#56 build: add makefile
  .github/workflows/tests.yml
  .gitignore
  Makefile
  benches/benchmarks.rs
  src/fee.rs
  src/lbp/tests.rs
  src/lib.rs
  src/liquidity_mining/tests.rs
  src/transcendental.rs
Labels: build

#62 refactor: omnipool - remove asset tvl calculations
  src/omnipool/invariants.rs
  src/omnipool/math.rs
  src/omnipool/tests.rs
  src/omnipool/types.rs
Labels: refactor
