Repository galacticcouncil/HydraDX-math, pull requests merged in 2022-06, with the labels that each got.

#30 refactor: remove fee struct
  Cargo.lock
  Cargo.toml
  src/fee.rs
Labels: refactor

#38 feat: stableswap add/remove liquid math
  Cargo.toml
  src/stableswap/math.rs
Labels: enhancement

#39 feat: add runtime-benchmarks features for stableswap to force max ite…
  Cargo.lock
  Cargo.toml
  src/stableswap/math.rs
Labels: enhancement

#40 feat: stableswap - expose calculate_d
  Cargo.lock
  Cargo.toml
  src/stableswap/math.rs
Labels: enhancement

#42 fix: xyk liquidity in rounding + share calculation
  Cargo.lock
  Cargo.toml
  src/tests.rs
  src/xyk.rs
Labels: bug

#43 feat: add xyk property tests
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/xyk/invariants.rs
  src/xyk/math.rs
  src/xyk/mod.rs
  src/xyk/tests.rs
Labels: enhancement
