Repository galacticcouncil/HydraDX-math, pull requests merged in 2022-10, with the labels that each got.

#71 fix: liquidity mining potential panic
  src/lib.rs
  src/liquidity_mining/liquidity_mining.rs
  src/liquidity_mining/tests.rs
Labels: bug

#70 fix: omnipool final rounding adjustments
  .gitignore
  proptest-regressions/omnipool/invariants.txt
  src/omnipool/invariants.rs
  src/omnipool/math.rs
Labels: bug

#61 fix: audit issues
  .gitignore
  proptest-regressions/omnipool/invariants.txt
  src/omnipool/invariants.rs
  src/omnipool/math.rs
  src/omnipool/tests.rs
  src/omnipool/types.rs
Labels: bug

#69 chore: upgrade to polkadot v0.9.28
  Cargo.lock
  Cargo.toml
  benches/benchmarks.rs
  rust-toolchain
  src/lib.rs
  src/transcendental.rs
Labels: chore

#47 feat: add omnipool math
  .gitignore
  Cargo.lock
  Cargo.toml
  proptest-regressions/omnipool/invariants.txt
  src/lib.rs
  src/omnipool/invariants.rs
  src/omnipool/math.rs
  src/omnipool/mod.rs
  src/omnipool/tests.rs
  src/omnipool/types.rs
  src/transcendental.rs
Labels: enhancement

#63 feat: stableswap v2
  Cargo.lock
  src/stableswap/math.rs
  src/stableswap/mod.rs
  src/stableswap/tests/invariants.rs
  src/stableswap/tests/mod.rs
  src/stableswap/tests/multi_assets.rs
  src/stableswap/tests/two_assets.rs
Labels: enhancement

#73 feat: add lbp prop tests for weight calculation
  Cargo.toml
  proptest-regressions/lbp/invariants.txt
  src/lbp/invariants.rs
  src/lbp/lbp.rs
  src/lbp/mod.rs
  src/lib.rs
  src/test_utils.rs
  src/xyk/invariants.rs
Labels: enhancement

#76 fix: lbp rounding
  src/lbp/lbp.rs
  src/lbp/tests.rs
Labels: bug

#75 fix: improve pow accuracy
  Cargo.lock
  Cargo.toml
  src/lbp/tests.rs
  src/lib.rs
  src/test_pow_accuracy.rs
  src/transcendental.rs
Labels: bug
